---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: fedora-demo-vm-hot-plug-disk
  namespace: demo-osmanemre
  ownerReferences:
    - apiVersion: kubevirt.io/v1
      blockOwnerDeletion: false
      kind: VirtualMachine
      name: fedora-demo-vm
      uid: ab5b2add-4fd3-4241-a423-e3286054d802
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  storage:
    resources:
      requests:
        storage: 10Gi
    storageClassName: ocs-storagecluster-ceph-rbd-replica2
  preallocation: false
  source:
    blank: {}
