apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: storage-demo-vm1-storage-demo-data1
  namespace: demo-osmanemre
spec:
  preallocation: false
  source:
    blank: {}
  storage:
    resources:
      requests:
        storage: 5Gi
    storageClassName: ocs-storagecluster-ceph-rbd-virtualization

